#!/bin/bash
cd /etc | ls -lh > ~/Desktop/Fish.txt
cd /run | ls -lh > ~/Desktop/Tank.txt
cat ~/Desktop/Fish.txt ~/Desktop/Tank.txt > ~/Desktop/FishTank.txt | sort ~/Desktop/FishTank.txt
sort -r ~/Desktop/FishTank.txt > ~/Desktop/TankFish.txt

#List contents of folders etc & run and redirect to separate .txt files
#Concatenate files to form a new .txt and sort list contents
#Sort list contents in reverse order and save to a new .txt file
